export const GET_ARTISTS_REQUEST = "GET_ARTISTS_REQUEST";
export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

export const GET_ARTIST_REQUEST = "GET_ARTIST_REQUEST";
export const GET_ARTIST_SUCCESS = "GET_ARTIST_SUCCESS";
export const GET_ARTIST_FAILURE = "GET_ARTIST_FAILURE";

export const INIT_ARTIST = "INIT_ARTIST";
export const SET_ARTIST = "SET_ARTIST";

export const GET_ALBUMS_REQUEST = "GET_ALBUMS_REQUEST";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";

export const GET_ALBUM_REQUEST = "GET_ALBUM_REQUEST";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAILURE = "GET_ALBUM_FAILURE";

export const INIT_ALBUM = "INIT_ALBUM";
export const SET_ALBUM = "SET_ALBUM";

