export const GET_ARTISTS_REQUEST = "GET_ARTISTS_REQUEST";
export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

export const GET_ARTIST_REQUEST = "GET_ARTIST_REQUEST";
export const GET_ARTIST_SUCCESS = "GET_ARTIST_SUCCESS";
export const GET_ARTIST_FAILURE = "GET_ARTIST_FAILURE";

export const INIT_ARTIST = "INIT_ARTIST";
export const SET_ARTIST = "SET_ARTIST";

export const GET_ALBUMS_REQUEST = "GET_ALBUMS_REQUEST";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";

export const GET_ALBUM_REQUEST = "GET_ALBUM_REQUEST";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAILURE = "GET_ALBUM_FAILURE";

export const INIT_ALBUM = "INIT_ALBUM";
export const SET_ALBUM = "SET_ALBUM";

export const GET_TRACKS_REQUEST = "GET_TRACKS_REQUEST";
export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_FAILURE = "GET_TRACKS_FAILURE";

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = "LOGOUT_USER";

export const SET_TRACK_IN_HISTORY_REQUEST = "SET_TRACK_IN_HISTORY_REQUEST";
export const SET_TRACK_IN_HISTORY_SUCCESS = "SET_TRACK_IN_HISTORY_SUCCESS";
export const SET_TRACK_IN_HISTORY_FAILURE = "SET_TRACK_IN_HISTORY_FAILURE";

export const GET_TRACKS_HISTORY_REQUEST = "GET_TRACKS_HISTORY_REQUEST";
export const GET_TRACKS_HISTORY_SUCCESS = "GET_TRACKS_HISTORY_SUCCESS";
export const GET_TRACKS_HISTORY_FAILURE = "GET_TRACKS_HISTORY_FAILURE";

export const ADD_ARTIST_SUCCESS = "ADD_ARTIST_SUCCESS";
export const ADD_ARTIST_FAILURE = "ADD_ARTIST_FAILURE";

export const DELETE_ARTIST_REQUEST = "DELETE_ARTIST_REQUEST";
export const DELETE_ARTIST_SUCCESS = "DELETE_ARTIST_SUCCESS";
export const DELETE_ARTIST_FAILURE = "DELETE_ARTIST_FAILURE";

export const PUBLISH_ARTIST_REQUEST = "PUBLISH_ARTIST_REQUEST";
export const PUBLISH_ARTIST_SUCCESS = "PUBLISH_ARTIST_SUCCESS";
export const PUBLISH_ARTIST_FAILURE = "PUBLISH_ARTIST_FAILURE";

export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS";
export const ADD_ALBUM_FAILURE = "ADD_ALBUM_FAILURE";

export const DELETE_ALBUM_REQUEST = "DELETE_ALBUM_REQUEST";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_FAILURE = "DELETE_ALBUM_FAILURE";

export const PUBLISH_ALBUM_REQUEST = "PUBLISH_ALBUM_REQUEST";
export const PUBLISH_ALBUM_SUCCESS = "PUBLISH_ALBUM_SUCCESS";
export const PUBLISH_ALBUM_FAILURE = "PUBLISH_ALBUM_FAILURE";

export const ADD_TRACK_SUCCESS = "ADD_TRACK_SUCCESS";
export const ADD_TRACK_FAILURE = "ADD_TRACK_FAILURE";

export const DELETE_TRACK_REQUEST = "DELETE_TRACK_REQUEST";
export const DELETE_TRACK_SUCCESS = "DELETE_TRACK_SUCCESS";
export const DELETE_TRACK_FAILURE = "DELETE_TRACK_FAILURE";

export const PUBLISH_TRACK_REQUEST = "PUBLISH_TRACK_REQUEST";
export const PUBLISH_TRACK_SUCCESS = "PUBLISH_TRACK_SUCCESS";
export const PUBLISH_TRACK_FAILURE = "PUBLISH_TRACK_FAILURE";
